service: junayeds-frontend
frameworkVersion: '3'

plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs16.x
  region: 'ap-northeast-1'
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
custom:
  s3Sync:
    buckets:
    - bucketName: '${env:FRONT_END_BUCKET}'
      localDir: build
      acl: public-read

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: '${env:FRONT_END_BUCKET}'
        WebsiteConfiguration:
          IndexDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                - 'arn:aws:s3:::${env:FRONT_END_BUCKET}/*'